# This is a basic workflow to help you get started with Actions

name: download-kernel

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "kernel-build"
    get-kernel-release:
        # The type of runner that the job will run on
        runs-on: ubuntu-22.04
        outputs:
            xarray: ${{ steps.create-array.outputs.array }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Fetch kernel release kernel.org
              id: create-array
              run: python3 package-array.py "$(curl -s https://www.kernel.org/releases.json)" >> $GITHUB_OUTPUT

    # This workflow contains a single job called "kernel-build"
    gen-kernel-package:
        # The type of runner that the job will run on
        runs-on: ubuntu-22.04
        needs: get-kernel-release

        strategy:
            matrix: ${{ fromJSON(needs.get-kernel-release.outputs.xarray) }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Install dependencies.
              run: |
                sudo apt update
                sudo apt upgrade -y
                sudo apt install -y build-essential gcc-aarch64-linux-gnu bison  devscripts        \
                qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support              \
                debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted            \
                udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3          \
                python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools         \
                python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools

            - name: Downloading source package [linux-${{ matrix.version }}]
              run: wget --quiet ${{ matrix.source }}

            - name: Extracting source package [linux-${{ matrix.version }}]
              run: tar -xf $(basename ${{ matrix.source }})

            - name: Patching source package [linux-${{ matrix.version }}]
              run: |
                patch --strip=1 --directory=linux-$KERNEL_VERSION < patch/oracular.patch
                patch --strip=1 --directory=linux-$KERNEL_VERSION < patch/overlay-dtc.patch
                cp -f kernel.config linux-$KERNEL_VERSION/debian.rockchip/config/config.common.ubuntu
                cp -f dts/rockchip/rk3588* linux-$KERNEL_VERSION/arch/arm64/boot/dts/rockchip
                dch                                                           \
                  --create                                                    \
                  --package linux-rockchip                                    \
                  --changelog linux-$KERNEL_VERSION/debian.rockchip/changelog \
                  --distribution oracular                                     \
                  --urgency medium                                            \
                  -v $KERNEL_VERSION-${KERNEL_RELEASE_DATE//-}                \
                  "Linux $KERNEL_VERSION ubuntu-rockchip oracular"
              shell: bash
              env:
                DEBEMAIL: nobara256@oracular.ubuntu
                DEBFULLNAME: Kurokawa Nobara
                DEB_BUILD_OPTIONS: nocheck
                KERNEL_VERSION: ${{ matrix.version }}
                KERNEL_RELEASE_DATE: ${{ matrix.released.isodate }}

            - name: Build linux-${{ matrix.version }} package
              run: fakeroot debian/rules clean defaultconfigs
              shell: bash
              working-directory: linux-${{ matrix.version }}
              env:
                CROSS_COMPILE: aarch64-linux-gnu-
                CC: aarch64-linux-gnu-gcc
                LANG: C
                DEB_BUILD_OPTIONS: nocheck

            - name: Upload linux-${{ matrix.version }} package
              uses: actions/upload-artifact@v4.5.0
              with:
                name: linux-${{ matrix.version }}-rockchip
                path: |
                  ./linux-${{ matrix.version }}/debian.rockchip/changelog
                  ./linux-${{ matrix.version }}/debian.rockchip/config/config.common.ubuntu
                compression-level: 0
                if-no-files-found: error