# This is a basic workflow to help you get started with Actions

name: download-kernel

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "kernel-build"
    get-kernel-source-array:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Get the kernel package list
              run: python3 package-array.py "$(curl -s https://www.kernel.org/releases.json)" >> $GITHUB_OUTPUT

    # This workflow contains a single job called "kernel-build"
    gen-kernel-package:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        needs: get-kernel-source-array

        strategy:
            matrix:
                package: ${{ fromJSON(needs.get-kernel-source-array.outputs.array) }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            - name: Dump the package
              run: echo ${{ matrix.package }}

            - name: Downloading linux-${{ matrix.package.version }}
              run: wget ${{ matrix.package.source }}

